config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :questions do
    member do
      get 'answer'
      post 'validate'
    end 
  end

  root 'home#index'

end

app/models/question.rb
class Question < ActiveRecord::Base

  validates_presence_of :answer, :query

  def correct_answer proposed_answer
    own_answer = self.answer.downcase.strip
    proposed_answer = proposed_answer.downcase.strip
    if own_answer == proposed_answer
      return true
    else
      if proposed_answer =~ /\A[-+]?[0-9]*\.?[0-9]+\Z/
        massaged_answer = proposed_answer.to_f.to_words
        if proposed_answer.to_words == own_answer
          return true
        end
      end
      if own_answer =~ /\A[-+]?[0-9]*\.?[0-9]+\Z/
        massaged_answer = own_answer.to_f.to_words
        if massaged_answer == proposed_answer
          return true
        end
      end
    end
    return false
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy, :answer]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  def answer
  end

  def validate
    @question = Question.find(params[:id])
    @pa = params[:proposed_answer]
    @is_correct = @question.correct_answer(@pa)
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:answer, :query)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML)
    markdown.render(text).html_safe
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/home/index.html.erb
<div class="row"> 
  <h2>Welcome to Quiz Master!</h2>
</div>
<div class="row"> 
  <p class="lead">Choose what you want to do:</p>
</div>      
<div class="row"> 
  <div class="col-xs-2">
  </div>
  <div class="col-xs-3">
    <%= button_to "Create a question", new_question_path, {method: :get, class: 'btn btn-lg btn-success'} %>
  </div>
  <div class="col-xs-1">
  </div>
  <div class="col-xs-6">
    <%= button_to "Answer a question", questions_path, {method: :get, class: 'btn btn-lg btn-info'} %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>QuizMaster</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <div class="header clearfix">
      <div class="jumbotron indent-vertical">
	<%= yield %>
      </div>
    </div>
  </div>
</body>
</html>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>
      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :query %>
    <%= f.text_field :query, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :answer %>
    <%= f.text_field :answer, class: "form-control" %>
  </div>
  <div class="row">
    <div class="col-xs-9">
    </div>
    <div class="col-xs-3">
      <div class="form-group push-right-form">
	<%= f.submit 'Add', class: "btn btn-lg btn-warning" %>
	<%= button_to "Back", home_index_path, {method: :get, class: 'btn btn-lg btn-success', id: 'back-butan'} %>
      </div>

    </div>
  </div>
<% end %>

app/views/questions/answer.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Query:</strong>
  <%= markdown @question.query %>
</p>
<p>
  <strong>Answer:</strong>
  <%= form_tag validate_question_path(@question) do %>
  <%= text_field_tag :proposed_answer %>
  <%= submit_tag "Validate"%>
  <% end %>
</p>



<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Available Questions</h2>

<table class="table">
  <thead>
    <tr>
      <th>Question text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= markdown question.query %></td>
        <td><%= button_to 'Answer', answer_question_path(question), {method: :get, class: 'btn btn-info sep'} %></td>
        <td><%= button_to 'Edit', edit_question_path(question), {method: :get, class: 'btn btn-warning sep'} %></td>
        <td><%= button_to 'Delete', question, {method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger sep'} %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back', home_index_path %>

app/views/questions/new.html.erb
<h2>New Question</h2>

<%= render 'form' %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Query:</strong>
  <%= markdown @question.query %>
</p>
<p>
  <strong>Answer:</strong>
  <%= markdown @question.answer %>
</p>


<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Questions list', questions_path %> |
<%= link_to 'Main Menu', home_index_path %>

app/views/questions/validate.html.erb
test